theme = "default"

[columns]
"runner" = 3


[[providers.prefixes]]
prefix = ">"
provider = "runner"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "?"
provider = "websearch"

[[providers.prefixes]]
prefix = "@"
provider = "archlinuxpkgs"

[[providers.prefixes]]
prefix = "/"
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "\"
provider = "unicode"

[[providers.prefixes]]
prefix = "#"
provider = "windows"


[[emergencies]]
text = "Firefox Developer Edition"
command = "firefox-developer-edition"

[[emergencies]]
text = "Wezterm"
command = "env -u WAYLAND_DISPLAY wezterm"

[[emergencies]]
text = "Kitty"
command = "kitty"

[[emergencies]]
text = "Elephant"
command = "elephant"
